# build.yml
name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/login-action@v2

      - name: Build Docker image
        run: |
          docker build -t cicd-model:1.0 .
          docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
          docker tag cicd-model:1.0 ${{ env.DOCKER_USERNAME }}/cicd-model:1.0
          docker push ${{ env.DOCKER_USERNAME }}/cicd-model:1.0