name: Test Docker Image

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  test:
    runs-on: windows-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: |
          docker pull ${{ env.DOCKER_USERNAME }}/cicd-model:1.0

      - name: Run tests
        run: |
          docker run --rm ${{ env.DOCKER_USERNAME }}/cicd-model:1.0 python test.py

    # Only run this job if the "Build and Push Docker Image" workflow is completed
    if: github.event.workflow_run.event == 'workflow_run' && github.event.workflow_run.workflow == 'Build and Push Docker Image'

    # If "Build and Push Docker Image" completed successfully, proceed with the tests. 
    # If it failed, force fail the test job.
    continue-on-error: ${{ github.event.workflow_run.conclusion != 'success' }}