name: Test
 
on:
  workflow_run:       
    workflows: ["Train"]
    types:
      - completed
 
jobs:
  pull-and-run:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
 
      - name: Pull Docker image
        run: docker pull arijitiisc/cicd-model:latest
 
      - name: Run Docker image and check score
        id: test
        run: |
          SCORE=$(docker run --rm  arijitiisc/cicd-model:latest)
          echo "Score: $SCORE"
          if (( $(echo "$SCORE > 0.35" | bc -l) )); then
            echo "Success: Score is greater than 0.35"
            echo "::set-output name=passed::true"
          else
            echo "Failure: Score is not greater than 0.35"
            echo "::set-output name=passed::false"
            exit 1
          fi
