name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types:
      - completed

jobs:
  pull-and-run:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: |
          docker pull ${{ env.DOCKER_USERNAME }}/cicd-model:1.0

      - name: Run tests
        id: test
        run: |
          OUTPUT=$(docker run --rm ${{ env.DOCKER_USERNAME }}/cicd-model:1.0 python test.py)
          echo "Score:"
          echo "$OUTPUT"
          if [[ $(echo "$OUTPUT > 0.5" | bc -l) == 1 ]]; then echo "Sufficient Accuracy"; else echo "Insufficient Accuracy" && exit 1; fi

    # Always run this job, regardless of the "Train" workflow status
    if: github.event.workflow_run.event == 'workflow_run' && github.event.workflow_run.workflow == 'Train'

    # Force fail the job if the "Train" workflow fails
    steps:
      - name: Force fail if "Train" workflow failed
        if: github.event.workflow_run.conclusion == 'failure'
        run: exit 1