name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    
    container:
      image: ${{ secrets.DOCKER_USERNAME }}/cicd-model:1.0
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          python test.py