name: Pull and Test Docker Image

on:
  pull_request:
    branches:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  pull-and-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        uses: actions/setup-python@v2
        with:
          image: ${{ secrets.REGISTRY_USERNAME }}/cicd-model:1.0:latest

      - name: Run test
        run: |
          docker run --rm ${{ secrets.REGISTRY_USERNAME }}/cicd-model:1.0 python test.py