name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types:
      - completed

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Check train.yml status
        id: check_train_status
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = context.payload;
            const status = payload.workflow_run.conclusion;
            return status;

      - name: Triggered by train.yml
        if: steps.check_train_status.outputs.status == 'success'
        run: echo "Train workflow passed, proceeding with tests."

      - name: Triggered by train.yml
        if: steps.check_train_status.outputs.status == 'failure'
        run: |
          echo "Train workflow failed, so not proceeding"
          exit 1

      - name: Run tests and check score
        if: steps.check_train_status.outputs.status == 'success'
        run: |
          OUTPUT=$(docker run --rm ${{ env.DOCKER_USERNAME }}/cicd-model:1.0 python test.py)
          echo "Score:"
          echo "$OUTPUT"
          if [[ $(echo "$OUTPUT > 0.35" | bc -l) == 1 ]]; then echo "Sufficient Accuracy"; else echo "Insufficient Accuracy" && exit 1; fi