name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types:
      - completed

jobs:
   pull-and-run:
    runs-on: windows-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: |
          docker pull ${{ env.DOCKER_USERNAME }}/cicd-model:1.0

      - name: Run tests
        run: |
          docker run --rm ${{ env.DOCKER_USERNAME }}/cicd-model:1.0 python test.py
          echo "Score:"
          echo "$OUTPUT"
          if [[ $(echo "$OUTPUT > 0.35" | bc -l) == 1 ]]; then echo "Sufficient Accuracy"; else echo "Insufficient Accuracy" && exit 1; fi