name: Train

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t cicd-model:1.0 .
          docker tag cicd-model:1.0 ${{ secrets.DOCKER_USERNAME }}/cicd-model:1.0
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-model:1.0

      - name: Store Build Status
        run: |
          echo "##@outputs=build_status=success"